#!/bin/bash
# ═══════════════════════════════════════════════════════════════════════════════
# NuvixoCoin VPS Setup Script
# Tested on Ubuntu 22.04 / 24.04 LTS
# Run as root: bash vps-setup.sh
# ═══════════════════════════════════════════════════════════════════════════════

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
NC='\033[0m'

print_step() { echo -e "\n${CYAN}══ $1 ${NC}"; }
print_ok()   { echo -e "${GREEN}✓ $1${NC}"; }
print_warn() { echo -e "${YELLOW}⚠ $1${NC}"; }
print_err()  { echo -e "${RED}✗ $1${NC}"; exit 1; }

echo -e "${CYAN}"
echo "  ███╗   ██╗██╗   ██╗██╗   ██╗██╗██╗  ██╗ ██████╗  ██████╗ ██████╗ ██╗███╗  ██╗"
echo "  ████╗  ██║██║   ██║██║   ██║██║╚██╗██╔╝██╔═══██╗██╔════╝██╔═══██╗██║████╗ ██║"
echo "  ██╔██╗ ██║██║   ██║██║   ██║██║ ╚███╔╝ ██║   ██║██║     ██║   ██║██║██╔██╗██║"
echo "  ██║╚██╗██║██║   ██║╚██╗ ██╔╝██║ ██╔██╗ ██║   ██║██║     ██║   ██║██║██║╚████║"
echo "  ██║ ╚████║╚██████╔╝ ╚████╔╝ ██║██╔╝╚██╗╚██████╔╝╚██████╗╚██████╔╝██║██║ ╚███║"
echo "  ╚═╝  ╚═══╝ ╚═════╝   ╚═══╝  ╚═╝╚═╝  ╚═╝ ╚═════╝  ╚═════╝ ╚═════╝ ╚═╝╚═╝  ╚══╝"
echo -e "${NC}"
echo -e "  ${CYAN}NuvixoCoin Node VPS Setup — v2.0.0${NC}"
echo -e "  ${YELLOW}nuvixocoin.com${NC}\n"

# ── Root check ────────────────────────────────────────────────────────────────
if [ "$EUID" -ne 0 ]; then
    print_err "Please run as root: sudo bash vps-setup.sh"
fi

# ── Collect config ────────────────────────────────────────────────────────────
print_step "Configuration"

read -p "  Enter your VPS public IP address: " VPS_IP
read -p "  Enter your bootstrap peer IP (your home node IP, or leave blank): " PEER_IP
read -s -p "  Enter admin password (will not be shown): " ADMIN_PASS
echo ""

if [ -z "$ADMIN_PASS" ] || [ ${#ADMIN_PASS} -lt 12 ]; then
    print_warn "Generating a strong admin password for you..."
    ADMIN_PASS=$(openssl rand -base64 32)
    echo "  Generated admin password: $ADMIN_PASS"
    echo "  SAVE THIS SOMEWHERE SAFE — you will need it to manage the node"
    echo ""
fi

NUVIXO_USER="nuvixo"
NUVIXO_DIR="/opt/nuvixocoin"
SERVICE_NAME="nuvixocoin"

# ── System update ─────────────────────────────────────────────────────────────
print_step "Updating system packages"
apt-get update -qq && apt-get upgrade -y -qq
print_ok "System updated"

# ── Java 17 ───────────────────────────────────────────────────────────────────
print_step "Installing Java 17"
apt-get install -y -qq openjdk-17-jdk-headless
java -version 2>&1 | head -1
print_ok "Java 17 installed"

# ── Create dedicated user ─────────────────────────────────────────────────────
print_step "Creating nuvixo system user"
if id "$NUVIXO_USER" &>/dev/null; then
    print_warn "User $NUVIXO_USER already exists"
else
    useradd -r -m -d /home/$NUVIXO_USER -s /bin/bash $NUVIXO_USER
    print_ok "User $NUVIXO_USER created"
fi

# ── Deploy NuvixoCoin ─────────────────────────────────────────────────────────
print_step "Deploying NuvixoCoin"
mkdir -p $NUVIXO_DIR
if [ -f "nuvixocoin-github-ready.zip" ]; then
    apt-get install -y -qq unzip
    unzip -q nuvixocoin-github-ready.zip -d $NUVIXO_DIR
    mv $NUVIXO_DIR/nuvixocoin/* $NUVIXO_DIR/
    rm -rf $NUVIXO_DIR/nuvixocoin
elif [ -d "/tmp/nuvixocoin" ]; then
    cp -r /tmp/nuvixocoin/* $NUVIXO_DIR/
else
    print_warn "NuvixoCoin files not found in current directory."
    print_warn "Please copy your nuvixocoin folder to $NUVIXO_DIR manually."
fi
print_ok "NuvixoCoin deployed to $NUVIXO_DIR"

# ── Write nxt.properties ──────────────────────────────────────────────────────
print_step "Writing node configuration"
mkdir -p $NUVIXO_DIR/conf
mkdir -p $NUVIXO_DIR/logs

cat > $NUVIXO_DIR/conf/nxt.properties << EOF
# NuvixoCoin Node Configuration
# Generated by vps-setup.sh on $(date)

nxt.adminPassword=$ADMIN_PASS
nxt.myAddress=$VPS_IP
nxt.myPlatform=NuvixoCoin Public Node
nxt.apiServerHost=0.0.0.0
nxt.shareMyAddress=true

EOF

if [ -n "$PEER_IP" ]; then
    echo "nxt.wellKnownPeers=$PEER_IP" >> $NUVIXO_DIR/conf/nxt.properties
    echo "nxt.defaultPeers=$PEER_IP" >> $NUVIXO_DIR/conf/nxt.properties
fi

print_ok "nxt.properties written"

# ── Compile ───────────────────────────────────────────────────────────────────
print_step "Compiling NuvixoCoin"
cd $NUVIXO_DIR
# Uses Gradle's application plugin distribution (installDist) rather than a
# fat jar — this keeps every dependency as its own untouched jar file in
# build/install/nuvixocoin/lib/, which avoids known packaging problems with
# signed jars (Bouncy Castle) and ServiceLoader-based SPI jars (Lucene) that
# only occur when jars get unpacked and merged into one combined archive.
if ! command -v gradle >/dev/null 2>&1; then
    apt-get install -y -qq gradle
fi
gradle wrapper --gradle-version 8.7
./gradlew installDist
print_ok "Compilation complete"

# ── Firewall ──────────────────────────────────────────────────────────────────
print_step "Configuring firewall"
apt-get install -y -qq ufw
ufw --force reset
ufw default deny incoming
ufw default allow outgoing
ufw allow ssh
ufw allow 27874/tcp comment "NuvixoCoin P2P"
ufw allow 7876/tcp comment "NuvixoCoin API"
ufw --force enable
print_ok "Firewall configured (SSH + P2P 27874 + API 7876)"

# ── Systemd service ───────────────────────────────────────────────────────────
print_step "Creating systemd service"
chown -R $NUVIXO_USER:$NUVIXO_USER $NUVIXO_DIR

cat > /etc/systemd/system/$SERVICE_NAME.service << EOF
[Unit]
Description=NuvixoCoin Blockchain Node
After=network.target
Wants=network-online.target

[Service]
Type=simple
User=$NUVIXO_USER
WorkingDirectory=$NUVIXO_DIR
ExecStart=$NUVIXO_DIR/build/install/nuvixocoin/bin/nuvixocoin
ExecStop=/bin/kill -SIGTERM \$MAINPID
Restart=on-failure
RestartSec=30
StandardOutput=append:$NUVIXO_DIR/logs/nuvixo.log
StandardError=append:$NUVIXO_DIR/logs/nuvixo.log
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable $SERVICE_NAME
systemctl start $SERVICE_NAME
sleep 3

if systemctl is-active --quiet $SERVICE_NAME; then
    print_ok "NuvixoCoin service started and enabled on boot"
else
    print_warn "Service may not have started. Check: journalctl -u $SERVICE_NAME -n 50"
fi

# ── Log rotation ──────────────────────────────────────────────────────────────
print_step "Setting up log rotation"
cat > /etc/logrotate.d/nuvixocoin << EOF
$NUVIXO_DIR/logs/*.log {
    daily
    rotate 14
    compress
    delaycompress
    missingok
    notifempty
    copytruncate
}
EOF
print_ok "Log rotation configured"

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo -e "${CYAN}═══════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  NuvixoCoin Node Setup Complete!${NC}"
echo -e "${CYAN}═══════════════════════════════════════════════════${NC}"
echo ""
echo -e "  ${YELLOW}Node directory:${NC}  $NUVIXO_DIR"
echo -e "  ${YELLOW}Public IP:${NC}       $VPS_IP"
echo -e "  ${YELLOW}P2P Port:${NC}        27874"
echo -e "  ${YELLOW}API Port:${NC}        7876"
echo -e "  ${YELLOW}Wallet UI:${NC}       http://$VPS_IP:7876"
echo ""
echo -e "  ${YELLOW}Useful commands:${NC}"
echo -e "  ${CYAN}systemctl status nuvixocoin${NC}   — check node status"
echo -e "  ${CYAN}systemctl restart nuvixocoin${NC}  — restart node"
echo -e "  ${CYAN}systemctl stop nuvixocoin${NC}     — stop node"
echo -e "  ${CYAN}tail -f $NUVIXO_DIR/logs/nuvixo.log${NC}  — live logs"
echo ""
echo -e "  ${YELLOW}Connect your home node:${NC}"
echo -e "  Add this to your local conf/nxt.properties:"
echo -e "  ${CYAN}nxt.wellKnownPeers=$VPS_IP${NC}"
echo -e "  ${CYAN}nxt.defaultPeers=$VPS_IP${NC}"
echo ""
echo -e "${GREEN}  Your chain is now publicly accessible!${NC}"
echo -e "${CYAN}═══════════════════════════════════════════════════${NC}"
